import { describe, it, expect, vi, beforeEach } from "vitest";
import request from "supertest";
import { v2 as cloudinary } from "cloudinary";
import { cloudinaryMock } from "./cloudinaryMock.js";
import { createUser, authHeader } from "./helpers.js";

vi.mock("../src/utils/cloudinary.js", () => cloudinaryMock);
const { app } = await import("../src/app.js");
const { Video } = await import("../src/models/video.model.js");
const agenda = (await import("../src/db/agendaSetup.js")).default;

const intent = async (user) =>
    (await request(app).post("/api/v2/videos/upload-intent").set(authHeader(user))).body.data;
const register = (user, body) => request(app).post("/api/v2/videos/from-upload").set(authHeader(user)).send(body);
const resourceFor = (publicId, overrides = {}) => ({
    public_id: publicId,
    secure_url: `https://res.cloudinary.com/test/video/upload/v1/${publicId}.mp4`,
    bytes: 5_000_000,
    duration: 42.5,
    ...overrides,
});

describe("direct upload to Cloudinary", () => {
    beforeEach(() => {
        vi.clearAllMocks();
        vi.spyOn(agenda, "schedule").mockResolvedValue(undefined);
    });

    it("signs an upload for a public id under the user's own prefix", async () => {
        const user = await createUser();
        const data = await intent(user);

        expect(data.publicId).toMatch(new RegExp(`^uploads/${user._id}/[0-9a-f-]{36}$`));
        expect(data.uploadUrl).toBe("https://api.cloudinary.com/v1_1/test/video/upload");
        expect(data.apiKey).toBe("test");
        // Cloudinary recomputes this signature from the same parameters and the account secret
        expect(data.signature).toBe(
            cloudinary.utils.api_sign_request({ public_id: data.publicId, timestamp: data.timestamp }, "test")
        );
        expect(data.chunkBytes).toBe(20 * 1024 * 1024);
    });

    it("registers the uploaded file and queues our processing job", async () => {
        const user = await createUser();
        const { publicId } = await intent(user);
        cloudinaryMock.getVideoResource.mockResolvedValueOnce(resourceFor(publicId));

        const res = await register(user, { publicId, title: "Straight to storage", category: "Music" });
        expect(res.status).toBe(201);
        expect(res.body.data).toMatchObject({
            status: "processing",
            sourcePublicId: publicId,
            duration: 42.5,
            category: "Music",
        });
        expect(res.body.data.thumbnailUrl).toBeUndefined(); // generated by the job
        expect(agenda.schedule).toHaveBeenCalledWith("in 5 seconds", "process video chunks", {
            videoId: expect.anything(),
        });
    });

    it("keeps a custom thumbnail sent with the registration", async () => {
        const user = await createUser();
        const { publicId } = await intent(user);
        cloudinaryMock.getVideoResource.mockResolvedValueOnce(resourceFor(publicId));

        const res = await request(app)
            .post("/api/v2/videos/from-upload")
            .set(authHeader(user))
            .field("publicId", publicId)
            .field("title", "With thumbnail")
            .attach("thumbnail", Buffer.from("img"), { filename: "t.png", contentType: "image/png" });
        expect(res.status).toBe(201);
        expect(res.body.data.thumbnailUrl).toMatch(/thumbnails\/up\d+\.png$/);
    });

    it("refuses someone else's upload, a missing upload, a duplicate and an oversized file", async () => {
        const [alice, mallory] = [await createUser(), await createUser()];
        const { publicId } = await intent(alice);

        expect((await register(mallory, { publicId, title: "stolen" })).status).toBe(403);

        cloudinaryMock.getVideoResource.mockResolvedValueOnce(null);
        expect((await register(alice, { publicId, title: "not uploaded yet" })).status).toBe(400);

        cloudinaryMock.getVideoResource.mockResolvedValueOnce(resourceFor(publicId));
        expect((await register(alice, { publicId, title: "first" })).status).toBe(201);
        expect((await register(alice, { publicId, title: "again" })).status).toBe(409);

        const big = await intent(alice);
        cloudinaryMock.getVideoResource.mockResolvedValueOnce(resourceFor(big.publicId, { bytes: 600 * 1024 * 1024 }));
        expect((await register(alice, { publicId: big.publicId, title: "huge" })).status).toBe(413);
        expect(cloudinaryMock.deleteFromCloudinary).toHaveBeenCalledWith(big.publicId, "video");

        expect((await register(alice, { publicId: "somewhere/else", title: "bad id" })).status).toBe(400);
        expect(await Video.countDocuments({})).toBe(1);
    });
});
